# 1. Web chính (Frontend)
server {
    listen 80;
    server_name ductuan71.top;

    location / {
        proxy_pass http://crypto_frontend_app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 2. Luồng API (Backend)
server {
    listen 80;
    server_name api.ductuan71.top;

    location / {
        proxy_pass http://crypto_backend_app:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

