name: CI/CD Pipeline cho CryptoCurrence v1

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        env: 
          API_URL: ${{ secrets.REACT_APP_API_URL }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 24700
          envs: API_URL
          script: |
            echo "=== BẮT ĐẦU PULL CODE VÀ DEPLOY TỰ ĐỘNG ==="
            cd ~/Tuan/CryptoCurrence
            git pull origin main
            echo "REACT_APP_API_URL=$API_URL" > ./KLTN_ITBlog_FE/.env
            chmod +x deploy-basic.sh
            ./deploy-basic.sh
